/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125384-gd936a51b27-20260701"
#endif /* AVUTIL_FFVERSION_H */
